import fs from "node:fs";

const required = [
  "index.html",
  ".github/CODEOWNERS",
  ".github/pull_request_template.md",
  ".github/workflows/audit.yml",
  ".github/ISSUE_TEMPLATE/config.yml",
  ".github/ISSUE_TEMPLATE/bug_report.yml",
  ".github/ISSUE_TEMPLATE/clause_review.yml",
  ".github/ISSUE_TEMPLATE/stakeholder_need.yml",
  ".claude/skills/sw-contract-scopeguard/SKILL.md",
  ".claude/skills/sw-contract-scopeguard/references/document-writing-recipes.md",
  ".claude/skills/sw-contract-scopeguard/references/documents/index.md",
  ".codex/skills/sw-contract-scopeguard/SKILL.md",
  ".codex/skills/sw-contract-scopeguard/references/document-writing-recipes.md",
  ".codex/skills/sw-contract-scopeguard/references/documents/index.md",
  "CONTRIBUTING.md",
  "SECURITY.md",
  "README.md",
  "assets/app.js",
  "assets/styles.css",
  "scripts/build-hwp-package.mjs",
  "scripts/audit-publish.mjs",
  "scripts/hwp/helpers.mjs",
  "scripts/hwp/docs/index.mjs",
  "scripts/hwp/docs/00-reference.mjs",
  "scripts/hwp/docs/01-input-summary.mjs",
  "scripts/hwp/docs/02-rfp-spec.mjs",
  "scripts/hwp/docs/03-contract-draft.mjs",
  "scripts/hwp/docs/04-acceptance-criteria.mjs",
  "scripts/hwp/docs/05-revision-request.mjs",
  "scripts/hwp/docs/06-change-request.mjs",
  "scripts/hwp/docs/07-meeting-minutes.mjs",
  "scripts/hwp/docs/08-delivery-confirmation.mjs",
  "scripts/hwp/docs/09-defect-report.mjs",
  "scripts/hwp/docs/10-payment-schedule.mjs",
  "scripts/hwp/docs/11-rights-handover.mjs",
  "scripts/hwp/docs/12-ops-handover.mjs",
  "scripts/hwp/docs/13-privacy-security.mjs",
  "scripts/hwp/docs/14-agreement-options.mjs",
  "scripts/hwp/docs/15-estimate-sheet.mjs",
  "scripts/hwp/docs/16-design-ux-appendix.mjs",
  "scripts/hwp/docs/17-revision-counting-appendix.mjs",
  "scripts/hwp/docs/18-feature-design-spec.mjs",
  "scripts/hwp/docs/22-lawyer-review-request.mjs",
  "scripts/xlsx/writer.mjs",
  "scripts/xlsx/workbooks/index.mjs",
  "templates/rfp-guide.md",
  "templates/sw-rfp-spec.md",
  "templates/acceptance-criteria.md",
  "templates/contract-risk-checklist.md",
  "templates/change-request.md",
  "templates/revision-request.md",
  "templates/meeting-minutes.md",
  "templates/delivery-confirmation.md",
  "templates/defect-report.md",
  "templates/agreement-options.md",
  "templates/contract-parameter-sheet.md",
  "templates/feature-design-spec.md",
  "templates/start-material-confirmation.md",
  "templates/acceptance-run-log.md",
  "templates/contract-risk-review.md",
  "data/contract-input.sample.json",
  "data/contract-input.design.sample.json",
  "data/contract-input.ops.sample.json",
  "data/question-overlays.sample.json",
  "data/event-schema.sample.json",
  "docs/prd.md",
  "docs/mvp-goal-and-exit-criteria.md",
  "docs/completion-audit.md",
  "docs/estimate-flow-completion-audit.md",
  "docs/legal-references.md",
  "docs/legal-mcp-findings.md",
  "docs/reference-bibliography.md",
  "docs/question-overlay-map.md",
  "docs/event-schema.md",
  "docs/skill-first-plan.md",
  "docs/pr-review-checklist.md",
  "docs/roadmap.md",
  "docs/lawyer-participation.md",
  "docs/stakeholder-needs.md",
  "docs/document-set.md",
  "docs/skill-proof.md",
];

let ok = true;
for (const path of required) {
  if (!fs.existsSync(path)) {
    console.error(`missing: ${path}`);
    ok = false;
  }
}

if (!ok) process.exit(1);
console.log("scopeguard-kr project files OK");
